name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    env:
      WORK_DIR: ${{ github.workspace }}
      PERSIST_DIR: /home/ubuntu/persisted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Create, verify, and persist .env file
      run: |
        echo "${{ secrets.PROD_ENV_FILE }}" > $WORK_DIR/.env
        echo "Work directory .env file hash:"
        md5sum $WORK_DIR/.env
        mkdir -p $PERSIST_DIR
        cp $WORK_DIR/.env $PERSIST_DIR/.env
        echo "Persisted .env file hash:"
        md5sum $PERSIST_DIR/.env
        echo "File permissions:"
        ls -l $WORK_DIR/.env $PERSIST_DIR/.env
        echo "File sizes:"
        wc -c $WORK_DIR/.env $PERSIST_DIR/.env
    - name: Verify persistence after job
      run: |
        echo "Work directory .env file hash after job:"
        md5sum $WORK_DIR/.env || echo "Work directory .env not found"
        echo "Persisted .env file hash after job:"
        md5sum $PERSIST_DIR/.env || echo "Persisted .env not found"
