name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Debug PROD_ENV_FILE secret
      run: |
        echo "PROD_ENV_FILE content:"
        echo "${{ secrets.PROD_ENV_FILE }}"
        echo "PROD_ENV_FILE length: ${#PROD_ENV_FILE}"
      env:
        PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}
    - name: Create and verify .env file
      run: |
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
        echo ".env file contents:"
        cat .env
        echo ".env file size:"
        wc -c < .env
        echo "Current working directory:"
        pwd
        echo "Directory contents:"
        ls -la
    - name: Persist .env file
      run: |
        mkdir -p $HOME/persisted
        cp .env $HOME/persisted/.env
        echo "Persisted .env file location: $HOME/persisted/.env"
        echo "Persisted .env file contents:"
        cat $HOME/persisted/.env
    - name: Check file permissions
      run: |
        echo ".env file permissions:"
        ls -l .env
        echo "Persisted .env file permissions:"
        ls -l $HOME/persisted/.env
    - name: Verify persistence
      run: |
        echo "Current directory .env contents:"
        cat .env
        echo "Persisted .env contents:"
        cat $HOME/persisted/.env
