name: Node.js CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Check if secrets are empty and create .env file
      run: |
        if [ -z "${{ secrets.PROD_ENV_FILE }}" ]; then
          echo "Error: PROD_ENV_FILE secret is empty"
          exit 1
        else
          echo "PROD_ENV_FILE secret is not empty"
          echo "Creating .env file..."
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
          echo ".env file created. File size:"
          wc -c < .env
        fi
    - name: Verify .env file (without exposing content)
      run: |
        if [ -s .env ]; then
          echo ".env file exists and is not empty"
          echo "Number of lines in .env:"
          wc -l < .env
          echo "First line of .env (sanitized):"
          sed 's/=.*/=REDACTED/' .env | head -n 1
        else
          echo "Error: .env file is empty or not created"
          exit 1
        fi
